### ISSUE TITLE
problem with Height 

### ISSUE THREAD

**Issue by ssageghi** [nkbt/react-collapse#178]
Hi I used collapse component and a button to open and close that 
what when I clicked that button nothing appear and height of component set to 0px 
and the item dosn't show
when I used fixed height it's ok 
![image](https://cloud.githubusercontent.com/assets/24605214/26546400/05f0c3b2-447f-11e7-851f-a2165c920a93.png)
how I can fix this

**Comment by halmos** [comment]
I can confirm similar issue in Safari 9.1.2. In particular, it seems to occur when the Collapse elements is given display: flex. It looks like the issue reported above also has element style with display: flex. Solution is to use wrapper divs for css layout and leave react collapse elements styles alone.

**Comment by nkbt** [comment]
Should be fixed in `react-collapse@4.0.3`

**Comment by ssageghi** [comment]
@nkbt I still have the problem
I click button and the collapse closed and height set to 0px, it's alright
but when I clicked button another time to open it the height doesn't change and collapse don't open

**Comment by nkbt** [comment]
Can you give an example on codepen to play with? It could be something to do with the container/children, then with Collapse

**Comment by ssageghi** [comment]
@nkbt ok I try

**Comment by ssageghi** [comment]
@nkbt can I post my code here?
it's a little hard for me

**Comment by nkbt** [comment]
It means I would need to create a codepen, I don't think I have much time for this at the moment.

You can clone https://codepen.io/nkbt/pen/MarzEg?editors=101 and update it with your case

**Comment by ssageghi** [comment]
@nkbt I try and it seems problem is on my local machine 
[https://codepen.io/ssageghi/pen/BdWJLW](url)
so can you give me a hint to where should I look for my problem and solved it 
I really appreciate that

**Comment by nkbt** [comment]
It is CSS/HTML, problem could be pretty much anywhere. Collapse or any of surrounding elements may actually have 0 height after certain update, so it is kind of legit case that collapse does not expand...

Plus add here react/redux/etc. For example component does not get update or smth - and it becomes impossible to know what exactly could go wrong without having workable code with repeatable issue.

I'll close the issue again, but feel free to reopen if you manage to reproduce it in isolation. 👐
